import "./globals.css";
import type { Metadata } from "next";
import { Rinkeby, ThirdwebProvider } from "./components/ThirdwebProvider";

import { Anton, Inter } from "next/font/google";

const anton = Anton({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-anton",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ThirdwebProvider activeChain={Rinkeby} clientId="your-client-id">
      <html lang="en">
        <body className={`${inter.variable} ${anton.variable}`}>
          {children}
        </body>
      </html>
    </ThirdwebProvider>
  );
}
